# Generated by Django 2.1.4 on 2018-12-15 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Berat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(verbose_name='Tanggal')),
                ('berat_max', models.IntegerField(default=0)),
                ('berat_min', models.IntegerField(default=0)),
            ],
        ),
    ]
