# Generated by Django 2.1.4 on 2018-12-15 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berat',
            name='tanggal',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 15, 22, 12, 40, 928472), verbose_name='Tanggal'),
        ),
    ]
