# Generated by Django 2.1.4 on 2018-12-15 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berat', '0002_auto_20181215_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='berat',
            name='diff',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='berat',
            name='tanggal',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 16, 0, 14, 15, 360842), verbose_name='Tanggal'),
        ),
    ]
